### ISSUE TITLE
Research/ticket 49/Comparing lifelong system logs

### ISSUE THREAD

**Issue by inexxt** [DPCS-team/DPCS#17]
After 1-2 years, a big part of collected logs and discovered bugs will be fixed and not important anymore.

However, some of the bugs may appear again or be important for people on older versions of the system.

When should we delete a log from our database? Should we create a separate database for older bugs?

Think about it, research, write about 0.5 pages summing up your ideas and present it during the meeting.

**Comment by MSusik** [comment]
> Krystyna Gajczyk
